### PR TITLE
create Code of Conduct

### PR DESCRIPTION
**Pull request by maddy020**
I have created a Code of conduct file in reactui-docs directory
Please review the changes in the PR and inform me if any changes are required
Solves issue #5

### CODE REVIEW

**Review by HassanBahati — APPROVED** [review]

**Comment by HassanBahati** [comment]
thank you for the contribution @maddy020 :clap:

**Comment by HassanBahati** [comment]
though i suggest that we move the `CODE_OF_CONDUCT` to the root directory. currently it appears to be inside `reactui-docs/CODE_OF_CONDUCT.md` 

could we please have it at the root(not inside any folder)

**Comment by maddy020** [comment]
Done with the changes 
Please review

**Comment by HassanBahati** [comment]
@maddy020 seems like you have deleted the file completely. Please add it to the root directory

**Review by HassanBahati — APPROVED** [review]
thank you @maddy020

**Pull request merged**
