### PR TITLE
chore(removed logo)

### PR DESCRIPTION
**Pull request by Pavan-Nambi**
hey i was not sure how to run this project as there are no scripts in package.json i have just updated code as i thought necessary for this can you look into tht and confirm?
closes isssue
https://github.com/OSCA-Kampala-Chapter/react-ui/issues/13#issue-1522226931

### CODE REVIEW

**Comment by HassanBahati** [comment]
> hey i was not sure how to run this project as there are no scripts in package.json i have just updated code as i thought necessary for this can you look into tht and confirm? closes isssue [#13 (comment)](https://github.com/OSCA-Kampala-Chapter/react-ui/issues/13#issue-1522226931)

hey @Pavan-Nambi thank you for pointing out this...i think we should add proper guidelines on how to run the project and where to find anything, let me create an issue for that and we look into it.

**Comment by HassanBahati** [comment]
@Pavan-Nambi  

under the [website directory](https://github.com/OSCA-Kampala-Chapter/react-ui/tree/main/website) is where we have the documentation that is built on top of [docusaurus v2](https://docusaurus.io/) which uses concepts of [react.js](https://reactjs.org/) so anyone that has done react can just work with it.

to run the  [website](https://github.com/OSCA-Kampala-Chapter/react-ui/tree/main/website) which also is where are going to be writing documentation.... 
1. move into the website directory `cd website`
2. install packages using `pnpm install` 
3. start the development server  `pnpm run start` which will open your browser at [http:localhost:3000](http:localhost:3000) 

[pnpm](https://pnpm.io/) is a package manger just like [npm](https://www.npmjs.com/) or [yarn](https://yarnpkg.com/)

**Review by HassanBahati — APPROVED** [review]
Looks Good to me. thank you for the contribution

**Comment by Pavan-Nambi** [comment]
> @Pavan-Nambi
> 
> under the [website directory](https://github.com/OSCA-Kampala-Chapter/react-ui/tree/main/website) is where we have the documentation that is built on top of [docusaurus v2](https://docusaurus.io/) which uses concepts of [react.js](https://reactjs.org/) so anyone that has done react can just work with it.
> 
> to run the [website](https://github.com/OSCA-Kampala-Chapter/react-ui/tree/main/website) which also is where are going to be writing documentation....
> 
> 1. move into the website directory `cd website`
> 2. install packages using `pnpm install`
> 3. start the development server  `pnpm run start` which will open your browser at http:localhost:3000
> 
> [pnpm](https://pnpm.io/) is a package manger just like [npm](https://www.npmjs.com/) or [yarn](https://yarnpkg.com/)

ya i got tht i can just to pnpm i and start but there are no scripts in package.json when i saw..? thats the reason i asked...

**Comment by Pavan-Nambi** [comment]
and are there any advantages to use pnpm over npm or yarn? i mostly see yarn everywhere npm sometimes 
@HassanBahati  just curious on how it differs? and why u preffered it...

**Comment by HassanBahati** [comment]
having pnpm installed wont mess up your yarn configurations. you can still use yarn in your other projects without any conflicts

**Comment by Pavan-Nambi** [comment]
> having pnpm installed wont mess up your yarn configurations. you can still use yarn in your other projects without any conflicts

ohh got it thankyou!

**Pull request merged**
